[2024-07-18T13:58:23.588+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: google_analytics_data_etl.task_transform_to_flat_by_operation manual__2024-07-17T15:00:53.249913+00:00 [queued]>
[2024-07-18T13:58:23.598+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: google_analytics_data_etl.task_transform_to_flat_by_operation manual__2024-07-17T15:00:53.249913+00:00 [queued]>
[2024-07-18T13:58:23.599+0000] {taskinstance.py:2171} INFO - Starting attempt 3 of 4
[2024-07-18T13:58:23.619+0000] {taskinstance.py:2192} INFO - Executing <Task(PythonOperator): task_transform_to_flat_by_operation> on 2024-07-17 15:00:53.249913+00:00
[2024-07-18T13:58:23.625+0000] {standard_task_runner.py:60} INFO - Started process 164 to run task
[2024-07-18T13:58:23.631+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'google_analytics_data_etl', 'task_transform_to_flat_by_operation', 'manual__2024-07-17T15:00:53.249913+00:00', '--job-id', '122', '--raw', '--subdir', 'DAGS_FOLDER/google_analytics_data_etl/google_analytics_data_etl.py', '--cfg-path', '/tmp/tmp1odt7ab7']
[2024-07-18T13:58:23.632+0000] {standard_task_runner.py:88} INFO - Job 122: Subtask task_transform_to_flat_by_operation
[2024-07-18T13:58:23.680+0000] {task_command.py:423} INFO - Running <TaskInstance: google_analytics_data_etl.task_transform_to_flat_by_operation manual__2024-07-17T15:00:53.249913+00:00 [running]> on host 3d44d7374020
[2024-07-18T13:58:23.770+0000] {taskinstance.py:2481} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='google_analytics_data_etl' AIRFLOW_CTX_TASK_ID='task_transform_to_flat_by_operation' AIRFLOW_CTX_EXECUTION_DATE='2024-07-17T15:00:53.249913+00:00' AIRFLOW_CTX_TRY_NUMBER='3' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-07-17T15:00:53.249913+00:00'
[2024-07-18T13:58:23.913+0000] {xcom.py:664} ERROR - keys must be str, int, float, bool or None, not tuple. If you are using pickle instead of JSON for XCom, then you need to enable pickle support for XCom in your *** config or make sure to decorate your object with attr.
[2024-07-18T13:58:23.914+0000] {taskinstance.py:2699} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/google_analytics_data_etl/logics/transform.py", line 60, in transform_to_flat_by_operation
    ti.xcom_push(key='transform_flat_group_event_name', value=data_to_dict)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/session.py", line 79, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 2981, in xcom_push
    XCom.set(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/session.py", line 76, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/xcom.py", line 247, in set
    value = cls.serialize_value(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/xcom.py", line 662, in serialize_value
    return json.dumps(value, cls=XComEncoder).encode("UTF-8")
  File "/usr/local/lib/python3.8/json/__init__.py", line 234, in dumps
    return cls(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/json.py", line 104, in encode
    return super().encode(o)
  File "/usr/local/lib/python3.8/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/local/lib/python3.8/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
TypeError: keys must be str, int, float, bool or None, not tuple
[2024-07-18T13:58:23.930+0000] {taskinstance.py:1138} INFO - Marking task as UP_FOR_RETRY. dag_id=google_analytics_data_etl, task_id=task_transform_to_flat_by_operation, execution_date=20240717T150053, start_date=20240718T135823, end_date=20240718T135823
[2024-07-18T13:58:23.946+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 122 for task task_transform_to_flat_by_operation (keys must be str, int, float, bool or None, not tuple; 164)
[2024-07-18T13:58:23.962+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-07-18T13:58:23.985+0000] {taskinstance.py:3281} INFO - 0 downstream tasks scheduled from follow-on schedule check
